version: "2"
exclude_patterns:
  - "__tests__/"
  - ".codeclimate.yml"
  - ".eslintignore"
  - ".eslintrc.js"
  - ".gitignore"
  - ".npmignore"
  - ".travis.yml"
  - "LICENSE"
  - "package.json"
  - "README.md"
